{{- range $i, $val := .Values.secrets.files }}
---
apiVersion: v1
kind: Secret
type: Opaque
{{ $split := splitList "/" $val.path -}}
{{ $file := last $split -}}
metadata: 
  name: {{ $val.name }}
  namespace: {{ $.Release.Namespace }}
data: 
  {{ print $file }}: {{ $.Files.Get $val.path | b64enc }}
{{ end }}

{{ range $path, $_ :=  .Files.Glob  "tmp/secrets/files/*" }}
---
apiVersion: v1
kind: Secret
type: Opaque
{{ $file := trimPrefix "tmp/secrets/files/" $path -}}
{{ $ext := $file | ext -}}
{{ $name := trimSuffix $ext $file -}}
metadata: 
  name: {{ print $name }}
  namespace: {{ $.Release.Namespace }}
data: 
  {{ print $file }}: {{ $.Files.Get $path | b64enc }}
{{ end }}